server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location = /vite.svg {
    try_files /vite.svg =404;
  }

  location /assets/ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}