apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config

data:
  PORT: "5000"
  MONGO_URL: "mongodb://mongo:27017/comanshanks"
  FRONTEND_URL: "http://localhost:8080"
  AUTH0_AUDIENCE: "ComanShanks-API"
  AUTH0_ISSUER_BASE_URL: "https://dev-lwupdghcnki7cu8h.us.auth0.com/"