export const cuisineList = [
	"Jollof Rice",
	"Pounded Yam",
	"Egusi Soup",
	"Fried Plantain",
	"Pepper Soup",
	"Bitterleaf Soup",
	"Efo Riro",
	"Moi Moi",
	"Afang Soup",
	"Okra Soup",
	"Akara",
	"Suya",
	"Ofada Rice",
	"Ogbono Soup",
	"Banga Soup",
	"Nkwobi",
	"Ewedu Soup",
	"Abacha",
	"Isi Ewu",
	"Tuwo Shinkafa",
	"Miyan Kuka",
	"Gbegiri Soup",
	"Kilishi",
	"Ukodo",
	"Edikang Ikong",
];
